### ISSUE TITLE
Register with same username

### ISSUE THREAD

**Issue by AbrarAhmed99** [jeremykenedy/laravel-auth#32] opened 2017-05-27 19:48 UTC
It gives me a error because a user with the username already exists and after register through facebook laravel tries to to register with same username:

```
QueryException in Connection.php line 647:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AbrarAhmed' for key 'users_name_unique' (SQL: insert into `users` (`name`, `first_name`, `last_name`, `email`, `password`, `token`, `activated`, `signup_sm_ip_address`, `updated_at`, `created_at`)
```

**Comment by jeremykenedy** [comment] 2017-05-27 19:52
Can you show me the whole stack track because the validator is in place to handle that.

**Comment by jeremykenedy** [comment] 2017-05-27 19:57
[Unable to reproduce error](https://s3-us-west-2.amazonaws.com/github-project-images/laravel-auth/unabletoreproduce.jpeg)

I am closing the issue as unable to reproduce.

**Comment by AbrarAhmed99** [comment] 2017-05-27 19:57
wait. What do you mean by stack trace?

**Closed by jeremykenedy** 2017-05-27 19:57 UTC

**Comment by jeremykenedy** [comment] 2017-05-27 19:59
the laravel error produced on your screen

**Comment by AbrarAhmed99** [comment] 2017-05-27 20:01
Here you go I have copied the source code into html file:
https://whatsmag.com/er.html

**Comment by jeremykenedy** [comment] 2017-05-27 20:05
Something seems off with the link you sent. It contains third party code in it such as your tracker:

```
/* <![CDATA[ */
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-54404819-4']);
_gaq.push(['_trackPageview']);
```

I cannot reproduce the error and this is protected here https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/RegisterController.php#L66

**Comment by AbrarAhmed99** [comment] 2017-05-27 20:07
that was inserted by cloudflare

**Comment by jeremykenedy** [comment] 2017-05-27 20:17
![Unable](https://s3-us-west-2.amazonaws.com/github-project-images/laravel-auth/laravel-auth-unable-to-replicate.gif)

**Comment by AbrarAhmed99** [comment] 2017-05-27 22:30
For the second time try registering with social network.

![my video gif 1](https://cloud.githubusercontent.com/assets/10310727/26524724/6e0c7700-42f1-11e7-8131-bb592991ba3c.gif)

**Comment by jeremykenedy** [comment] 2017-05-28 00:08
It even worked fine social media logins and error handling. Again, I cannot reproduce and your gif shows no sign of an error and is not helpful.
