### ISSUE TITLE
Problems with PHP 7.0.19, and How to Update?

### ISSUE THREAD

**Issue by jywong** [jeremykenedy/laravel-auth#113] opened 2018-02-14 20:00 UTC
Jeremy, thank you for the time you have spent on this! What an incredible way to start a project.

I know this isn't your fault... but my hosting provider is stuck on PHP 7.0.19, and there is a call to Symfony's css-selector that blows up, whenever an email is being sent from the system, like for a forgotten password.

"Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)"
on this line:
public function translateExists(XPathExpr $xpath, string $attribute, ?string $value): XPathExpr

Here's a screenshot:
https://we.tl/7NQkYdvMjJ

If I switch the PHP version on my development machine to 7.1.8, it works fine. Unfortunately my host is saying that it will be weeks or more before they approve that version.

Is there a part that I can comment out or change so that it doesn't use this? maybe send plain text emails instead?

And a second question... What's the best way to update the laravel-auth code to the latest version AFTER it has been integrated into another project?

Thanks!
Joey

**Comment by jywong** [comment] 2018-02-14 20:04
I think this is the same as issue #106. Again, I think it is a PHP bug.. just wondering if there was any way to work around it temporarily!

**Comment by jeremykenedy** [comment] 2018-02-14 20:09
Do you have the email configured in the .env file?

**Comment by jywong** [comment] 2018-02-15 07:32
Yes I do. I can simply switch the PHP version from 7.0.19 to 7.1.8 and it works fine. Apparently it is Symfony. Symfony 4 apparently requires PHP 7.1.

So my real question is now... can I bypass Symfony? or use a previous version of it somehow? what is it used for?

I suspect I have to modify one of the install packages..?

**Comment by jywong** [comment] 2018-02-18 19:34
Is there any way to send the emails without using the Symfony package? or using the 3.0 version?

**Comment by jeremykenedy** [comment] 2018-02-18 23:26
I think that would be done by changing the email driver and the logic associated with it.

The mail would need to be changed use notifications as well might assist with the issue: https://laravel.com/docs/5.5/notifications

In the [laravel2step](https://github.com/jeremykenedy/laravel2step/blob/master/src/app/Notifications/SendVerificationCodeEmail.php) package and the account restoration section of this project, I am using the notifications which may give some help.

Here is some info on sparkpost:
https://medium.com/@petehouston/send-mail-with-sparkpost-in-laravel-b5e30a941ebf

Here some on Mandrill:
https://blog.sarav.co/integrate-mandrill-mail-server-in-laravel/

Here some for sendinblue:
https://github.com/agence-webup/laravel-sendinblue 
https://apidocs.sendinblue.com/downloads-and-api-wrappers/ 

A completely different approach using Amazon and Laravel que:
https://tuts.codingo.me/sending-emails-over-queue-with-aws-ses
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-smtp-php.html

**Comment by jeremykenedy** [comment] 2018-02-19 04:40
Since the issue is with symphony I am going to close the issue but still want to help where I can, please let me know if there is anything I can do further. Thank you

**Closed by jeremykenedy** 2018-02-19 04:40 UTC
